### PR TITLE
build electron 3.0 for macOS

### PR DESCRIPTION
**Pull request by the-j0k3r**
Need this for Atom 1.39.1 electron 3.x

EDIT, a test build shows this fails, might need python 2.7 or something else. =(

### CODE REVIEW

**Comment by oznu** [comment]
I should have read your edit before merging, builds for Electron 3.0.0 fail on macOS.

**Comment by the-j0k3r** [comment]
Yea, sorry, I submited PR while my test build was running and it appeared to succeed at this step, but it did not, hence the edit.

The errors make no sense to me, it could be the electron 3.x needs python 2.7 because node-gyp version in use there, or something else. I have no experience compiling for macOS let alone this type of thing.

Any thoughts?

**Comment by the-j0k3r** [comment]
Well I managed to compile it but have recursion warnings https://travis-ci.org/the-j0k3r/node-pty-prebuilt-multiarch/jobs/567251405

chnageset https://github.com/the-j0k3r/node-pty-prebuilt-multiarch/compare/4f8e6a33e25c...ada9e4ae5ae9

**Comment by the-j0k3r** [comment]
OK found the issue full compiled no errors in macOS

https://travis-ci.org/the-j0k3r/node-pty-prebuilt-multiarch/jobs/567260399

The breaking change was https://github.com/microsoft/node-pty/commit/5db10ca4e3970a65492ee0bb7c1f02766d7d6628

I reverted this portion 

```cc
/* forkpty */
/* http://www.gnu.org/software/gnulib/manual/html_node/forkpty.html */
#if defined(__GLIBC__) || defined(__CYGWIN__)
#include <pty.h>
#elif defined(__APPLE__) || defined(__OpenBSD__) || defined(__NetBSD__)
/**
 * From node v0.10.28 (at least?) there is also a "util.h" in node/src, which
 * would confuse the compiler when looking for "util.h".
 */
#if NODE_VERSION_AT_LEAST(0, 10, 28)
#include <../include/util.h>
#else
#include <util.h>
#endif
#elif defined(__FreeBSD__)
#include <libutil.h>
#elif defined(__sun)
#include <stropts.h> /* for I_PUSH */
#else
#include <pty.h>
#endif
```

Compile sucessful, but I imagine a real fix has to account for the old node removal I doubt they would accept a patch partially reverting this. Im not an expert here or anything close to it. But this fixes it.

**Comment by the-j0k3r** [comment]
OK https://github.com/microsoft/node-pty/pull/339 is made upstream

**Comment by the-j0k3r** [comment]
@oznu see https://github.com/microsoft/node-pty/pull/339#issuecomment-519660578

Essentially upstream is saying they wont patch this there, and for our project until Atom 1.41.0 is out with Electron 4.x support we are pretty much stuffed in macOS, this release is still months away with 1.40.0 still before that with still electron 3.x current is 1.39.1 with electron 3.x

Would you consider carrying a patch until then? Im willing to look out for it and submit the fixes and removals from here.

**Comment by oznu** [comment]
I can build this for you in a different branch, with a different tag.

**Comment by the-j0k3r** [comment]
Would that be available via npm?

**Comment by oznu** [comment]
It would be available via npm. Please submit a PR with the required changes and I'll sort out the rest.

**Comment by the-j0k3r** [comment]
if you make the branch I can get to it asap. Thanks for this. =)

**Comment by oznu** [comment]
No problem, I can merge your PR into a new branch after you submit it.

**Pull request merged**
